stages:
  - test
  - deploy



test:
  stage: test

  image: nixos/nix:latest

  before_script:
    - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
    - nix-channel --update
    - nix-env -i cabal-install cabal2nix
    - mkdir -p public

  script:
    - make coverage
    - cp -r dist/hpc/vanilla/html/test public/coverage
    - make bench
    - cp bench.html public'

  artifacts:
    paths:
      - public

pages:
  stage: deploy

  dependencies:
    - test

  # it needs a script even if we do nothing
  script: ls -lRh

  artifacts:
    paths:
      - public

  only:
    - master
