stages:
  - test
  - deploy



test:
  stage: test

  image: nixos/nix:latest

  before_script:
    - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
    - nix-channel --update

  script:
    - "nix-shell -p cabal-install -p 'haskellPackages.ghcWithPackages (pkgs: [pkgs.shake])' --run './build coverage && ./build bench'"

  artifacts:
    paths:
      - public

pages:
  stage: deploy

  dependencies:
    - test

  # it needs a script even if we do nothing
  script: ls -lRh

  artifacts:
    paths:
      - public

  only:
    - master
