stages:
  - test
  - deploy



test:
  stage: test

  image: nixorg/nix:latest

  before_script:
    - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
    - nix-channel --update
    - nix-env -f '<nixpkgs>' -iA wget cabal-install cabal2nix ghc glibcLocales


  script:
    - "nix-shell -p 'haskellPackages.ghcWithPackages (pkgs: [pkgs.shake])' --run './build -v'"
      # some encoding issue if we don't have locales
    - "export LOCALE_ARCHIVE=/root/.nix-profile/lib/locale/locale-archive"
    - "export LANG=en_US.UTF-8"
    - "export LC_ALL=en_US.UTF-8"
    - "./_shake/build coverage && ./_shake/build bench && echo 'Done.'"


  artifacts:
    paths:
      - public

pages:
  stage: deploy

  dependencies:
    - test

  # it needs a script even if we do nothing
  script: ls -lRh

  artifacts:
    paths:
      - public

  only:
    - master
