stages:
  - test
  - deploy



test:
  stage: test

  image: nixorg/nix:latest

  before_script:
    - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
    - nix-channel --update
    - nix-env -f '<nixpkgs>' -iA wget cabal-install cabal2nix ghc


  script:
    - "nix-shell -p 'haskellPackages.ghcWithPackages (pkgs: [pkgs.shake])' --run './build -v'"
      # some encoding issue if we don't redirect output
    - "./_shake/build coverage && echo 'Executing benchmarks...' && ./_shake/build bench >/dev/null 2>&1 && echo 'Done.' || echo 'Error'"


  artifacts:
    paths:
      - public

pages:
  stage: deploy

  dependencies:
    - test

  # it needs a script even if we do nothing
  script: ls -lRh

  artifacts:
    paths:
      - public

  only:
    - master
