stages:
  - test
  - deploy



test:
  stage: test

  image: nixos/nix:latest

  before_script:
    - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
    - nix-channel --update
    - mkdir -p public

  script:
    - > nix-shell --attr withCabal release.nix --run '
    cabal clean && cabal configure --enable-tests --enable-coverage &&
    cabal build && cabal test && cp -r dist/hpc/vanilla/html/test public/coverage &&
    cabal clean && cabal configure --enable-benchmarks && cabal build &&
    ./dist/build/evalbench/evalbench -o bench.html &&
    cp bench.html public'

  artifacts:
    paths:
      - public

pages:
  stage: deploy

  dependencies:
    - test

  artifacts:
    paths:
      - public

  only:
    - master
