name:                hbf
version:             "0.1.0.2"
license:             GPL-3
license-file:        LICENSE
author:              Sebastian Galkin
maintainer:          paraseba@gmail.com
copyright:           Sebastian Galkin, 2018

synopsis:            An optimizing Brainfuck compiler and evaluator
description:
  "hbf is a compiler and executor of Brainfuck programs. It provides
   two executables: @hbfc@ the Brainfuck compiler, and @hbf@ the virtual
   machine that executes compiled Brainfuck programs."

homepage:            https://github.com/paraseba/hbf
bug-reports:         https://github.com/paraseba/hbf/issues

category:            Language
tested-with: "GHC == 8.2.1, GHC == 8.2.2, GHC == 8.4.1, GHC == 8.4.2, GHC == 8.4.3"

extra-source-files:
  - README.md
  - ChangeLog.md
  - tests/allfeatures.bf
  - tests/factor.bf
  - tests/squares.bf

git: git@github.com:paraseba/hbf.git

flags:

  dump:
    # dump files will be available after cabal build in dist/build/src/HBF/
    description: Dump stg and core files
    manual: true
    default: False

  profile:
    description: Enable profiling in benchmarks
    manual: True
    default: False

ghc-options:
  - -Wall
  - -fwarn-incomplete-record-updates
  - -fwarn-monomorphism-restriction

dependencies:
  - base >= 4.10.0.0 && < 4.13
  - vector >= 0.12.0.1
  - primitive >= 0.6.2.0
  - text >= 1.2.2.0
  - bytestring >= 0.10.8.0
  - transformers >= 0.5.2.0
  - filepath >= 1.4.1.2
  - parsec >= 3.1.13.0
  - binary >= 0.8.5.1
  - optparse-applicative >= 0.14.0.0
  - deepseq >= 1.4.3.0

library:
  exposed-modules:
    - HBF.Types
    - HBF.Parser
    - HBF.Eval
    - HBF.Compiler

  source-dirs:      src

  when:
    - condition: flag(dump)
      ghc-options:
        - -ddump-simpl
        - -ddump-stg
        - -ddump-to-file
        - -dsuppress-idinfo
        - -dsuppress-coercions
        - -dsuppress-type-applications
        - -dsuppress-uniques
    - condition: flag(profile)
      ghc-options:
        - -fprof-auto


executables:

  hbfc:
    main: Main.hs
    source-dirs:  src/exe/hbfc
    dependencies:
      - hbf

  hbf:
    main: Main.hs
    source-dirs: src/exe/hbf
    dependencies:
      - hbf

    when:
      - condition: flag(profile)
        ghc-options:
          - -fprof-auto
          - '"-with-rtsopts=-p -s -h -i0.05"'

tests:
  doctest:
    source-dirs: tests
    main: doctest.hs
    dependencies:
      - hbf
      - doctest
    ghc-options:
      - -threaded
      - -with-rtsopts=-N
    other-modules: []

  test:
    source-dirs: tests
    main: test.hs
    dependencies:
      - hbf
      - temporary >= 1.2.0.3
      - HUnit >= 1.3.1.0
      - hedgehog >= 0.5
      - hedgehog-checkers >= 0.1.0.0
      - smallcheck >= 1.1
      - tasty >= 0.11.2.1
      - tasty-hedgehog >= 0.1.0.0
      - tasty-smallcheck >= 0.8
      - tasty-hunit >= 0.9.2
      - tasty-discover >= 2.0.0

    ghc-options:
      - -threaded
      - -with-rtsopts=-N

    other-modules:
      - ParserTest
      - CompilerTest
      - EvalTest
      - IntegrationTests
      - Helper

benchmarks:
  evalbench:
    source-dirs: bench
    main: Main.hs
    dependencies:
      - hbf
      - criterion >= 1.1.4.0

    ghc-options:
      - -threaded
      - -with-rtsopts=-N
